[package]
name = "roc_std"
description = "Rust representations of Roc data structures"

authors = ["The Roc Contributors"]
edition = "2021"
license = "UPL-1.0"
repository = "https://github.com/roc-lang/roc"
version = "0.0.1"

[dependencies]
arrayvec = "0.7.2"
serde = { version = "1.0.153", optional = true }
static_assertions = "1.1.0"

[dev-dependencies]
libc = "0.2.139"
pretty_assertions = "1.3.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
serde_json = "1.0.94"

[features]
serde = ["dep:serde"]
std = []

[package.metadata.cargo-udeps.ignore]
development = ["quickcheck_macros", "serde_json"]
